#!/usr/bin/env bash

set -e

DIR="$(cd $(dirname "$0") && cd .. && pwd )"

if [ `uname` == "Linux" ]; then
  TAG="$(cat ${DIR}/config/blobs.yml | grep 'windows2019fs/windows2016fs-' |  grep -oP '\d*\.\d*\.\d*')"
else
  TAG="$(cat ${DIR}/config/blobs.yml | grep 'windows2019fs/windows2016fs-' |  grep -o '\d*\.\d*\.\d*')"
fi

go get code.cloudfoundry.org/hydrator/cmd/hydrate

$GOPATH/bin/hydrate \
  download \
  -image cloudfoundry/windows2016fs \
  -tag ${TAG} \
  -outputDir ${DIR}/blobs/windows2019fs

bosh create-release "${@:1}"
